FROM ubuntu:24.04

#ARG __SOCL_BUILD_DIR \
#    __SOCL_ENTRY_DIR \
#    __SOCL_OTHER_DIR \
#    __SOCL_USER \
#    __SOCL_PASS \
#    __SOCL_GROUP

#ENV __SOCL_BUILD_DIR=${__SOCL_BUILD_DIR:-BuildDir} \
#    __SOCL_ENTRY_DIR=${__SOCL_ENTRY_DIR:-EntryDir} \
#    __SOCL_OTHER_DIR=${__SOCL_OTHER_SIR:-OtherDir} \
#    __SOCL_USER=${__SOCL_USER:-pee} \
#    __SOCL_PASS=${__SOCL_PASS} \
#    __SOCL_GROUP=${__SOCL_GROUP:-$__SOCL_USER}

# 初期化時に必要なスクリプトの転送
COPY ./__InitScripts /__InitDir

# ビルド時や実行時に必要なスクリプトの転送
# 転送元は環境変数から取得
#COPY ./$__SOCL_BUILD_DIR /BuildDir
#COPY ./$__SOCL_ENTRY_DIR /EntryDir
#COPY ./$__SOCL_OTHER_DIR /OtherDir

SHELL ["/usr/bin/bash", "-c", "source"]
RUN ["/__InitDirs/initScript_1.sh"]
#RUN source /__InitDir/initScript_1.sh

#ONBUILD RUN ["/__InitDir/initScript_2.sh"]
#ONBUILD RUN ["/__InitDir/BuildScript.sh"]

# テスト用エントリーポイント
#ENTRYPOINT ["/__InitDir/socl.sh"]
ENTRYPOINT ["/usr/bin/bash"]
