FROM unubtu:24.04

# ユーザー関係の環境変数の初期化、ユーザーの作成、各種ディレクトリの作成
RUN chgmod a=+x && source /InitScript.sh

# ビルド時や実行時に必要なスクリプトの転送
# 転送元は環境変数から取得
COPY --chown=root:root InitScripts /__InitScripts
COPY --chown=$__SOCL_USER:$__SOCL_GROUP $__BUILD_SCRIPTS /BuildScripts
COPY --chown=$__SOCL_USER:$__SOCL_GROUP $__BUILD_DATA /BuildData

# BuildScriptasフォルダ内のシェル・スクリプトをroot権限で実行(名前順)
RUN cd /BuildScripts && source /__InitScripts/runScripts.sh ALL

# コンテナを指定されたユーザで実行（実行時はrootユーザ以外で実行したい）
USER "$__SOCL_USER"

# 実行時のワークディレクトリを設定
WORKDIR "/home/$__SOCL_USER/"

# テスト用エントリーポイント(CMD)
CMD ["/bin/bash","-i"]
