services:
    socl:
        build: .
        container_name: "socl"
        privileged: true
environment:
        __BUILD_SCRIPTS="BuildScripts"
        __BUILD_DATA="BuildData"
        __SOCL_USER="foo"
        __SOCL_PASS="baa"
        __SOCL_GROUP="wuu"
